<?php

namespace Database\Seeders;

use App\Models\Karyawan;
use App\Models\UnitKerja;
use Illuminate\Database\Seeder;

class KaryawanSeeder extends Seeder
{
    public function run(): void
    {
        $unitKerjaMap = UnitKerja::pluck('id', 'nama_unit');

        foreach (['IT', 'Keuangan', 'SDM', 'Operasional', 'Bag. Umum', 'Logistik'] as $namaUnit) {
            if (! $unitKerjaMap->has($namaUnit)) {
                throw new \RuntimeException("Unit kerja {$namaUnit} wajib tersedia sebelum KaryawanSeeder dijalankan.");
            }
        }

        $karyawans = [
            [
                'nik' => '2026001',
                'nama_lengkap' => 'Ahmad Rizki',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1990-05-12',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671011205900001',
                'npwp' => '09.123.451.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Teknik Informatika',
                'nama_sekolah' => 'Universitas Sriwijaya',
                'tahun_lulus' => 2012,
                'nama_pasangan' => 'Siti Aminah',
                'jumlah_anak' => 2,
                'unit_kerja_id' => $unitKerjaMap['IT'],
                'tanggal_masuk_kerja' => '2018-01-15',
                'jabatan' => 'Staff IT',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/001/PUSKOPDIT/2018',
                'tanggal_sk_pengangkatan' => '2018-01-15',
                'gaji_pokok' => 6500000,
            ],
            [
                'nik' => '2026002',
                'nama_lengkap' => 'Dewi Sartika',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1992-08-21',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671016108920002',
                'npwp' => '09.123.452.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Akuntansi',
                'nama_sekolah' => 'Universitas Sriwijaya',
                'tahun_lulus' => 2014,
                'nama_pasangan' => 'Bambang Wijaya',
                'jumlah_anak' => 1,
                'unit_kerja_id' => $unitKerjaMap['Keuangan'],
                'tanggal_masuk_kerja' => '2017-03-01',
                'jabatan' => 'Analyst Keuangan',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/002/PUSKOPDIT/2017',
                'tanggal_sk_pengangkatan' => '2017-03-01',
                'gaji_pokok' => 7000000,
            ],
            [
                'nik' => '2026003',
                'nama_lengkap' => 'Budi Santoso',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1988-01-10',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Kristen',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671011001880003',
                'npwp' => '09.123.453.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Manajemen SDM',
                'nama_sekolah' => 'Universitas Indonesia',
                'tahun_lulus' => 2011,
                'nama_pasangan' => 'Ratna Sari',
                'jumlah_anak' => 2,
                'unit_kerja_id' => $unitKerjaMap['SDM'],
                'tanggal_masuk_kerja' => '2015-06-10',
                'jabatan' => 'HR Supervisor',
                'status_karyawan' => 'Kontrak',
                'nomor_sk_pengangkatan' => 'SK/003/PUSKOPDIT/2015',
                'tanggal_sk_pengangkatan' => '2015-06-10',
                'gaji_pokok' => 5500000,
            ],
            [
                'nik' => '2026004',
                'nama_lengkap' => 'Citra Lestari',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1995-11-02',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'nomor_ktp' => '1671014211950004',
                'npwp' => '09.123.454.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Ekonomi',
                'nama_sekolah' => 'Universitas Sriwijaya',
                'tahun_lulus' => 2017,
                'unit_kerja_id' => $unitKerjaMap['Operasional'],
                'tanggal_masuk_kerja' => '2019-09-01',
                'jabatan' => 'Koordinator Operasional',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/004/PUSKOPDIT/2019',
                'tanggal_sk_pengangkatan' => '2019-09-01',
                'gaji_pokok' => 6200000,
            ],
            [
                'nik' => '2026005',
                'nama_lengkap' => 'Eko Prasetyo',
                'tempat_lahir' => 'Lubuklinggau',
                'tanggal_lahir' => '1991-04-18',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671011804910005',
                'npwp' => '09.123.455.7-301.000',
                'pendidikan_terakhir' => 'SMA/SMK',
                'jurusan' => 'IPS',
                'nama_sekolah' => 'SMK Negeri 1 Lubuklinggau',
                'tahun_lulus' => 2009,
                'nama_pasangan' => 'Yuni Astuti',
                'jumlah_anak' => 1,
                'tanggal_mengundurkan_diri' => '2025-12-31',
                'unit_kerja_id' => $unitKerjaMap['Bag. Umum'],
                'tanggal_masuk_kerja' => '2016-02-01',
                'jabatan' => 'Staff Umum',
                'status_karyawan' => 'Honorer',
                'nomor_sk_pengangkatan' => 'SK/005/PUSKOPDIT/2016',
                'tanggal_sk_pengangkatan' => '2016-02-01',
                'gaji_pokok' => 4800000,
            ],
            [
                'nik' => '2026006',
                'nama_lengkap' => 'Fitriani Wulandari',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1993-03-07',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671014703930006',
                'npwp' => '09.123.456.7-301.000',
                'pendidikan_terakhir' => 'D3',
                'jurusan' => 'Logistik',
                'nama_sekolah' => 'Politeknik Sriwijaya',
                'tahun_lulus' => 2013,
                'nama_pasangan' => 'Rudi Hartono',
                'jumlah_anak' => 1,
                'unit_kerja_id' => $unitKerjaMap['Logistik'],
                'tanggal_masuk_kerja' => '2018-07-15',
                'jabatan' => 'Staff Logistik',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/006/PUSKOPDIT/2018',
                'tanggal_sk_pengangkatan' => '2018-07-15',
                'gaji_pokok' => 5800000,
            ],
            [
                'nik' => '2026007',
                'nama_lengkap' => 'Gunawan Saputra',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1987-09-25',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671012509870007',
                'npwp' => '09.123.457.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Teknik Informatika',
                'nama_sekolah' => 'Universitas Bina Darma',
                'tahun_lulus' => 2010,
                'nama_pasangan' => 'Dewi Kartika',
                'jumlah_anak' => 3,
                'unit_kerja_id' => $unitKerjaMap['IT'],
                'tanggal_masuk_kerja' => '2014-01-05',
                'jabatan' => 'Network Engineer',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/007/PUSKOPDIT/2014',
                'tanggal_sk_pengangkatan' => '2014-01-05',
                'gaji_pokok' => 7200000,
            ],
            [
                'nik' => '2026008',
                'nama_lengkap' => 'Hesti Purnama',
                'tempat_lahir' => 'Prabumulih',
                'tanggal_lahir' => '1996-02-14',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'nomor_ktp' => '1671015402960008',
                'npwp' => '09.123.458.7-301.000',
                'pendidikan_terakhir' => 'D3',
                'jurusan' => 'Akuntansi',
                'nama_sekolah' => 'Politeknik Sriwijaya',
                'tahun_lulus' => 2016,
                'unit_kerja_id' => $unitKerjaMap['Keuangan'],
                'tanggal_masuk_kerja' => '2020-04-01',
                'jabatan' => 'Staff Keuangan',
                'status_karyawan' => 'Kontrak',
                'nomor_sk_pengangkatan' => 'SK/008/PUSKOPDIT/2020',
                'tanggal_sk_pengangkatan' => '2020-04-01',
                'gaji_pokok' => 5200000,
            ],
            [
                'nik' => '2026009',
                'nama_lengkap' => 'Indra Kusuma',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1994-07-30',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'nomor_ktp' => '1671013007940009',
                'npwp' => '09.123.459.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Psikologi',
                'nama_sekolah' => 'Universitas Sriwijaya',
                'tahun_lulus' => 2016,
                'unit_kerja_id' => $unitKerjaMap['SDM'],
                'tanggal_masuk_kerja' => '2019-02-01',
                'jabatan' => 'Staff SDM',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/009/PUSKOPDIT/2019',
                'tanggal_sk_pengangkatan' => '2019-02-01',
                'gaji_pokok' => 5600000,
            ],
            [
                'nik' => '2026010',
                'nama_lengkap' => 'Joko Widodo Prasetya',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1989-12-05',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671010512890010',
                'npwp' => '09.123.460.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Manajemen',
                'nama_sekolah' => 'Universitas Trisakti',
                'tahun_lulus' => 2012,
                'nama_pasangan' => 'Wulan Sari',
                'jumlah_anak' => 2,
                'unit_kerja_id' => $unitKerjaMap['Operasional'],
                'tanggal_masuk_kerja' => '2016-08-01',
                'jabatan' => 'Staff Operasional',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/010/PUSKOPDIT/2016',
                'tanggal_sk_pengangkatan' => '2016-08-01',
                'gaji_pokok' => 5400000,
            ],
            [
                'nik' => '2026011',
                'nama_lengkap' => 'Kartika Sari',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1997-06-19',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'nomor_ktp' => '1671015906970011',
                'npwp' => '09.123.461.7-301.000',
                'pendidikan_terakhir' => 'SMA/SMK',
                'jurusan' => 'IPS',
                'nama_sekolah' => 'SMA Negeri 1 Palembang',
                'tahun_lulus' => 2015,
                'unit_kerja_id' => $unitKerjaMap['Bag. Umum'],
                'tanggal_masuk_kerja' => '2021-01-10',
                'jabatan' => 'Resepsionis',
                'status_karyawan' => 'Kontrak',
                'nomor_sk_pengangkatan' => 'SK/011/PUSKOPDIT/2021',
                'tanggal_sk_pengangkatan' => '2021-01-10',
                'gaji_pokok' => 4200000,
            ],
            [
                'nik' => '2026012',
                'nama_lengkap' => 'Lukman Hakim',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1986-10-11',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671011110860012',
                'npwp' => '09.123.462.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Teknik Industri',
                'nama_sekolah' => 'Universitas Sriwijaya',
                'tahun_lulus' => 2009,
                'nama_pasangan' => 'Siti Nurhaliza',
                'jumlah_anak' => 2,
                'unit_kerja_id' => $unitKerjaMap['Logistik'],
                'tanggal_masuk_kerja' => '2013-05-01',
                'jabatan' => 'Kepala Gudang',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/012/PUSKOPDIT/2013',
                'tanggal_sk_pengangkatan' => '2013-05-01',
                'gaji_pokok' => 6800000,
            ],
            [
                'nik' => '2026013',
                'nama_lengkap' => 'Maya Anggraini',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1998-01-28',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Kawin',
                'nomor_ktp' => '1671016801980013',
                'npwp' => '09.123.463.7-301.000',
                'pendidikan_terakhir' => 'D3',
                'jurusan' => 'Manajemen Informatika',
                'nama_sekolah' => 'Politeknik Sriwijaya',
                'tahun_lulus' => 2018,
                'unit_kerja_id' => $unitKerjaMap['IT'],
                'tanggal_masuk_kerja' => '2021-09-01',
                'jabatan' => 'Staff Support',
                'status_karyawan' => 'Kontrak',
                'nomor_sk_pengangkatan' => 'SK/013/PUSKOPDIT/2021',
                'tanggal_sk_pengangkatan' => '2021-09-01',
                'gaji_pokok' => 5000000,
            ],
            [
                'nik' => '2026014',
                'nama_lengkap' => 'Nugroho Adi Wibowo',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1990-03-22',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671012203900014',
                'npwp' => '09.123.464.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Akuntansi',
                'nama_sekolah' => 'Universitas Sriwijaya',
                'tahun_lulus' => 2013,
                'nama_pasangan' => 'Rina Wati',
                'jumlah_anak' => 1,
                'unit_kerja_id' => $unitKerjaMap['Keuangan'],
                'tanggal_masuk_kerja' => '2017-11-01',
                'jabatan' => 'Kasir',
                'status_karyawan' => 'Tetap',
                'nomor_sk_pengangkatan' => 'SK/014/PUSKOPDIT/2017',
                'tanggal_sk_pengangkatan' => '2017-11-01',
                'gaji_pokok' => 4900000,
            ],
            [
                'nik' => '2026015',
                'nama_lengkap' => 'Oktavia Rahma',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1993-05-09',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Kawin',
                'nomor_ktp' => '1671014905930015',
                'npwp' => '09.123.465.7-301.000',
                'pendidikan_terakhir' => 'S1',
                'jurusan' => 'Manajemen SDM',
                'nama_sekolah' => 'Universitas Sriwijaya',
                'tahun_lulus' => 2015,
                'nama_pasangan' => 'Anton Budiman',
                'jumlah_anak' => 1,
                'tanggal_mengundurkan_diri' => '2025-10-15',
                'unit_kerja_id' => $unitKerjaMap['SDM'],
                'tanggal_masuk_kerja' => '2018-03-01',
                'jabatan' => 'Staff Rekrutmen',
                'status_karyawan' => 'Honorer',
                'nomor_sk_pengangkatan' => 'SK/015/PUSKOPDIT/2018',
                'tanggal_sk_pengangkatan' => '2018-03-01',
                'gaji_pokok' => 5100000,
            ],
        ];

        foreach ($karyawans as $data) {
            Karyawan::updateOrCreate(
                ['nik' => $data['nik']],
                $data
            );
        }

        $atasanPerNik = [
            '2026001' => '2026007',
            '2026006' => '2026012',
            '2026008' => '2026002',
            '2026009' => '2026003',
            '2026010' => '2026004',
            '2026011' => '2026004',
            '2026013' => '2026007',
            '2026014' => '2026002',
            '2026015' => '2026003',
        ];
        $ids = Karyawan::whereIn('nik', array_unique([
            ...array_keys($atasanPerNik),
            ...array_values($atasanPerNik),
        ]))->pluck('id', 'nik');

        foreach ($atasanPerNik as $nik => $nikAtasan) {
            Karyawan::where('nik', $nik)->update(['atasan_langsung_id' => $ids[$nikAtasan]]);
        }
    }
}
