<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Katalog jenis barang per golongan penyusutan
    |--------------------------------------------------------------------------
    |
    | Sumber awal: daftar_item_kategori_penyusutan.md (151 item).
    | Golongan dan masa manfaat mengacu pada PMK 72 Tahun 2023. Katalog ini
    | menjadi allow-list untuk input barang agar jenis barang dan golongannya
    | tidak dapat dipasangkan secara sembarang dari request.
    |
    */
    'item_per_golongan' => [
        'Bukan Bangunan - Kelompok 1' => [
            'Access point Wi-Fi',
            'Alarm keamanan',
            'Alat pemadam api ringan (APAR)',
            'Amplifier',
            'Blender',
            'Bor tangan listrik',
            'Deep fryer',
            'Digital signage',
            'DVR / NVR CCTV',
            'Food processor',
            'Gergaji listrik portabel',
            'Gerinda tangan',
            'Hand pallet',
            'Handy talky (HT)',
            'Hard disk eksternal',
            'Juicer',
            'Kalkulator meja',
            'Kamera CCTV',
            'Kamera digital',
            'Kamera video',
            'Ketel listrik',
            'Kompor gas',
            'Kompor listrik / induksi',
            'Komputer all-in-one',
            'Komputer desktop',
            'Kotak perkakas',
            'Kursi kerja kayu',
            'Kursi rotan',
            'Kursi tamu kayu',
            'Laptop / notebook',
            'Layar presentasi elektrik',
            'Lemari kayu',
            'Meja kerja kayu',
            'Meja rapat kayu',
            'Meja resepsionis kayu',
            'Mesin absensi sidik jari',
            'Mesin akses pintu',
            'Mesin deteksi uang',
            'Mesin faksimile',
            'Mesin fotokopi',
            'Mesin hitung uang',
            'Mesin jilid',
            'Mesin kasir / cash register',
            'Mesin kopi',
            'Mesin laminating',
            'Mesin las portabel',
            'Mesin penghancur kertas',
            'Microwave',
            'Mikrofon kabel',
            'Mikrofon nirkabel',
            'Mini PC',
            'Mixer',
            'Modem',
            'Monitor CCTV',
            'Monitor komputer',
            'NAS (Network Attached Storage)',
            'Network switch',
            'Oven',
            'PABX / IP PBX',
            'Papan interaktif / smart board',
            'Partisi kantor kayu yang dapat dipindah',
            'Pemanggang roti',
            'Perangkat POS lengkap',
            'Perangkat video conference',
            'Printer inkjet',
            'Printer kartu anggota',
            'Printer laser',
            'Printer thermal / struk',
            'Proyektor',
            'Rak buku kayu',
            'Rice cooker',
            'Router',
            'Scanner barcode',
            'Scanner dokumen',
            'Sepeda',
            'Sepeda listrik',
            'Sepeda motor',
            'Server',
            'Smoke detector',
            'Sofa rangka kayu',
            'Sound system',
            'Speaker aktif',
            'Stabilizer listrik',
            'Tablet',
            'Tangga portabel',
            'Telepon meja',
            'Telepon seluler / smartphone dinas',
            'Televisi',
            'UPS',
            'Water boiler',
            'Webcam konferensi',
            'Workstation',
        ],
        'Bukan Bangunan - Kelompok 2' => [
            'AC cassette',
            'AC split',
            'AC standing',
            'Air cooler',
            'Air purifier',
            'Bus / minibus',
            'Container penyimpanan',
            'Exhaust fan',
            'Filing cabinet',
            'Kios container yang dapat dipindah',
            'Kipas angin berdiri',
            'Kipas angin dinding',
            'Kipas angin meja',
            'Kursi kerja logam',
            'Lemari arsip logam',
            'Locker logam',
            'Meja kasir logam',
            'Meja kerja logam',
            'Mobil operasional / MPV',
            'Mobil penumpang',
            'Mobil pick-up',
            'Mobil van',
            'Partisi logam yang dapat dipindah',
            'Rak gudang logam',
            'Rak jaringan berbahan logam',
            'Speed boat',
            'Truk',
        ],
        'Bukan Bangunan - Kelompok 3' => [
            'Baterai penyimpanan energi',
            'Brankas / safe',
            'Chiller',
            'Dishwasher',
            'Dispenser air',
            'Forklift',
            'Freezer',
            'Genset',
            'Inverter tenaga surya',
            'Kompresor udara',
            'Kulkas / lemari es',
            'Mesin cuci',
            'Mesin pembuat es',
            'Mesin poles lantai',
            'Panel surya',
            'Pompa air',
            'Pressure washer',
            'Tangki air portabel',
            'Vacuum cleaner',
            // PMK 72/2023 menetapkan jenis bukan bangunan yang tidak
            // tercantum dalam lampiran memakai masa manfaat Kelompok 3.
            'Jenis lain yang tidak tercantum dalam katalog',
        ],
        'Bukan Bangunan - Kelompok 4' => [
            'Gerbong kereta',
            'Kapal di atas 1.000 DWT',
            'Lokomotif',
            'Mesin berat konstruksi',
        ],
        'Bangunan - Permanen' => [
            'Garasi permanen',
            'Gedung kantor permanen',
            'Gudang permanen',
            'Pintu vault / ruang khasanah',
            'Pos jaga permanen',
            'Toko / unit usaha permanen',
        ],
        'Bangunan - Bukan Permanen' => [
            'Bangunan kayu sementara',
            'Barak / gudang sementara',
            'Booth / kios sementara',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Tarif fiskal tahunan
    |--------------------------------------------------------------------------
    |
    | Nilai disimpan sebagai desimal agar dapat langsung dipakai kalkulator.
    | Saldo menurun hanya berlaku untuk harta bukan bangunan.
    |
    */
    'tarif' => [
        'garis_lurus' => [
            'Bukan Bangunan - Kelompok 1' => '0.25',
            'Bukan Bangunan - Kelompok 2' => '0.125',
            'Bukan Bangunan - Kelompok 3' => '0.0625',
            'Bukan Bangunan - Kelompok 4' => '0.05',
            'Bangunan - Permanen' => '0.05',
            'Bangunan - Bukan Permanen' => '0.10',
        ],
        'saldo_menurun' => [
            'Bukan Bangunan - Kelompok 1' => '0.50',
            'Bukan Bangunan - Kelompok 2' => '0.25',
            'Bukan Bangunan - Kelompok 3' => '0.125',
            'Bukan Bangunan - Kelompok 4' => '0.10',
        ],
    ],
];
