<?php

return [
    'cache_key' => 'platform.features.statuses.v1',

    'features' => [
        'product_requests' => [
            'label' => 'Request Produk',
            'description' => 'Pengajuan, percakapan, lampiran, dan pemantauan request produk.',
            'icon' => 'bi-chat-square-text',
            'category' => 'Produk & akun pribadi',
            'routes' => ['product-requests.*'],
        ],
        'my_profile' => [
            'label' => 'Data Saya',
            'description' => 'Ringkasan profil kepegawaian milik pengguna yang sedang masuk.',
            'icon' => 'bi-person-vcard',
            'category' => 'Produk & akun pribadi',
            'routes' => ['me.profile'],
        ],
        'my_attendance' => [
            'label' => 'Absensi Saya',
            'description' => 'Riwayat kehadiran pribadi pengguna.',
            'icon' => 'bi-calendar-check',
            'category' => 'Produk & akun pribadi',
            'routes' => ['me.attendance'],
        ],
        'my_salary_slips' => [
            'label' => 'Slip Gaji Saya',
            'description' => 'Portal slip gaji pribadi dan penerbitan slip kepada akun karyawan.',
            'icon' => 'bi-receipt',
            'category' => 'Produk & akun pribadi',
            'routes' => ['me.salary-slips.*'],
        ],
        'work_units' => [
            'label' => 'Unit Kerja',
            'description' => 'Master unit kerja dan seluruh aksi pengelolaannya.',
            'icon' => 'bi-building',
            'category' => 'SDM & kehadiran',
            'routes' => ['unit-kerja.*'],
        ],
        'employees' => [
            'label' => 'Karyawan',
            'description' => 'Data karyawan, akun, riwayat, dan dokumen terkait.',
            'icon' => 'bi-people',
            'category' => 'SDM & kehadiran',
            'routes' => ['karyawan.*'],
        ],
        'attendance' => [
            'label' => 'Absensi',
            'description' => 'Pencatatan dan pemeriksaan absensi karyawan.',
            'icon' => 'bi-calendar3',
            'category' => 'SDM & kehadiran',
            'routes' => ['absensi.*'],
        ],
        'holidays' => [
            'label' => 'Hari Libur',
            'description' => 'Master, impor, dan sinkronisasi hari libur.',
            'icon' => 'bi-calendar-x',
            'category' => 'SDM & kehadiran',
            'routes' => ['hari-libur.*'],
        ],
        'employee_reports' => [
            'label' => 'Laporan Kepegawaian',
            'description' => 'Tampilan, cetak, dan ekspor laporan kepegawaian.',
            'icon' => 'bi-bar-chart-line',
            'category' => 'SDM & kehadiran',
            'routes' => ['laporan.kepegawaian*'],
        ],
        'attendance_reports' => [
            'label' => 'Laporan Absensi',
            'description' => 'Tampilan, cetak, dan ekspor laporan absensi.',
            'icon' => 'bi-calendar-check',
            'category' => 'SDM & kehadiran',
            'routes' => ['laporan.absensi*'],
        ],
        'salary_components' => [
            'label' => 'Komponen Gaji',
            'description' => 'Master komponen perhitungan gaji.',
            'icon' => 'bi-sliders',
            'category' => 'Penggajian',
            'routes' => ['komponen-gaji.*'],
        ],
        'salary_transactions' => [
            'label' => 'Transaksi Gaji',
            'description' => 'Pengolahan, penerbitan, dan pencetakan transaksi gaji.',
            'icon' => 'bi-cash-stack',
            'category' => 'Penggajian',
            'routes' => ['transaksi-gaji.*'],
        ],
        'payroll_reports' => [
            'label' => 'Laporan Penggajian',
            'description' => 'Tampilan, cetak, dan ekspor laporan penggajian.',
            'icon' => 'bi-cash-coin',
            'category' => 'Penggajian',
            'routes' => ['laporan.penggajian*'],
        ],
        'inventory' => [
            'label' => 'Inventaris Barang',
            'description' => 'Data barang, kondisi, foto, dokumen, barcode, dan QR code.',
            'icon' => 'bi-box-seam',
            'category' => 'Manajemen aset',
            'routes' => ['barang.*'],
        ],
        'depreciation_reports' => [
            'label' => 'Penyusutan Aset',
            'description' => 'Tampilan, cetak, dan ekspor laporan penyusutan.',
            'icon' => 'bi-graph-down',
            'category' => 'Manajemen aset',
            'routes' => ['laporan.penyusutan*'],
        ],
        'inventory_reports' => [
            'label' => 'Laporan Inventaris',
            'description' => 'Tampilan, cetak, dan ekspor laporan inventaris.',
            'icon' => 'bi-clipboard-data',
            'category' => 'Manajemen aset',
            'routes' => ['laporan.inventaris*'],
        ],
        'users' => [
            'label' => 'Manajemen Pengguna',
            'description' => 'Pembuatan, perubahan, dan penonaktifan akun pengguna.',
            'icon' => 'bi-person-gear',
            'category' => 'Administrasi',
            'routes' => ['pengguna.*'],
        ],
        'roles' => [
            'label' => 'Role & Hak Akses',
            'description' => 'Pengelolaan role dan permission tenant.',
            'icon' => 'bi-shield-lock',
            'category' => 'Administrasi',
            'routes' => ['role.*'],
        ],
        'app_settings' => [
            'label' => 'Pengaturan Aplikasi',
            'description' => 'Identitas koperasi, hari operasional, dan template slip gaji.',
            'icon' => 'bi-gear',
            'category' => 'Administrasi',
            'routes' => ['pengaturan.*'],
        ],
        'cooperatives' => [
            'label' => 'Manajemen Koperasi',
            'description' => 'Pembuatan dan perubahan data koperasi oleh Super Admin.',
            'icon' => 'bi-building-gear',
            'category' => 'Administrasi',
            'routes' => ['koperasi.index', 'koperasi.create', 'koperasi.store', 'koperasi.edit', 'koperasi.update'],
        ],
    ],
];
