<?php

return [
    'max_image_dimension' => 8000,
    'max_image_megapixels' => 40,
    'txt_preview_bytes' => 200 * 1024,
    'staging_expiry_hours' => 24,
    'max_parallel_uploads' => 3,

    'clamav' => [
        'host' => env('CLAMAV_HOST', 'clamav'),
        'port' => (int) env('CLAMAV_PORT', 3310),
        'connect_timeout_seconds' => (float) env('CLAMAV_CONNECT_TIMEOUT', 3),
        'read_timeout_seconds' => (int) env('CLAMAV_READ_TIMEOUT', 60),
        'chunk_bytes' => 8192,
    ],

    'capacity' => [
        'disk' => env('UPLOAD_CAPACITY_DISK', 'local'),
        'emergency_min_free_percent' => (float) env('UPLOAD_EMERGENCY_MIN_FREE_PERCENT', 5),
        'emergency_min_free_bytes' => (int) env('UPLOAD_EMERGENCY_MIN_FREE_BYTES', 2 * 1024 * 1024 * 1024),
        'warning_percentages' => [75, 85, 95],
    ],

    'features' => [
        'async' => env('UPLOAD_ASYNC_ENABLED', false),
        'scan_required' => env('UPLOAD_SCAN_REQUIRED', false),
        'x_accel' => env('UPLOAD_X_ACCEL_ENABLED', false),
    ],

    'policies' => [
        'employee_photo' => [
            'label' => 'Foto karyawan',
            'extensions' => ['jpg', 'jpeg', 'png', 'webp'],
            'mime_by_extension' => [
                'jpg' => ['image/jpeg'],
                'jpeg' => ['image/jpeg'],
                'png' => ['image/png'],
                'webp' => ['image/webp'],
            ],
            'max_files' => 1,
            'max_file_kilobytes' => 15 * 1024,
            'max_total_kilobytes' => 15 * 1024,
            'preview' => true,
            'camera' => true,
            'crop' => ['aspect_ratio' => 1],
            'client_max_dimension' => 1280,
            'help' => 'JPG, JPEG, PNG, atau WebP · maks. 15 MB · foto akan dipotong 1:1.',
        ],
        'asset_photo' => [
            'label' => 'Foto barang',
            'extensions' => ['jpg', 'jpeg', 'png', 'webp'],
            'mime_by_extension' => [
                'jpg' => ['image/jpeg'],
                'jpeg' => ['image/jpeg'],
                'png' => ['image/png'],
                'webp' => ['image/webp'],
            ],
            'max_files' => 1,
            'max_file_kilobytes' => 15 * 1024,
            'max_total_kilobytes' => 15 * 1024,
            'preview' => true,
            'camera' => true,
            'crop' => null,
            'client_max_dimension' => 2560,
            'help' => 'JPG, JPEG, PNG, atau WebP · maks. 15 MB.',
        ],
        'asset_gallery' => [
            'label' => 'Galeri barang',
            'extensions' => ['jpg', 'jpeg', 'png', 'webp'],
            'mime_by_extension' => [
                'jpg' => ['image/jpeg'],
                'jpeg' => ['image/jpeg'],
                'png' => ['image/png'],
                'webp' => ['image/webp'],
            ],
            'max_files' => 5,
            'max_file_kilobytes' => 15 * 1024,
            'max_total_kilobytes' => 50 * 1024,
            'preview' => true,
            'camera' => false,
            'crop' => null,
            'client_max_dimension' => 2560,
            'help' => 'Maks. 5 foto · 15 MB per file · total 50 MB.',
        ],
        'logo' => [
            'label' => 'Logo',
            'extensions' => ['jpg', 'jpeg', 'png', 'webp'],
            'mime_by_extension' => [
                'jpg' => ['image/jpeg'],
                'jpeg' => ['image/jpeg'],
                'png' => ['image/png'],
                'webp' => ['image/webp'],
            ],
            'max_files' => 1,
            'max_file_kilobytes' => 15 * 1024,
            'max_total_kilobytes' => 15 * 1024,
            'preview' => true,
            'camera' => false,
            'crop' => null,
            'client_max_dimension' => 2560,
            'help' => 'JPG, JPEG, PNG, atau WebP · maks. 15 MB · rasio asli dipertahankan.',
        ],
        'business_documents' => [
            'label' => 'Dokumen',
            'extensions' => ['pdf', 'jpg', 'jpeg', 'png'],
            'mime_by_extension' => [
                'pdf' => ['application/pdf'],
                'jpg' => ['image/jpeg'],
                'jpeg' => ['image/jpeg'],
                'png' => ['image/png'],
            ],
            'max_files' => 5,
            'max_file_kilobytes' => 20 * 1024,
            'max_total_kilobytes' => 50 * 1024,
            'preview' => true,
            'camera' => false,
            'crop' => null,
            'help' => 'PDF, JPG, JPEG, atau PNG · maks. 5 file · 20 MB per file · total 50 MB.',
        ],
        'product_attachments' => [
            'label' => 'Lampiran',
            'extensions' => ['pdf', 'jpg', 'jpeg', 'png', 'webp', 'txt'],
            'mime_by_extension' => [
                'pdf' => ['application/pdf'],
                'jpg' => ['image/jpeg'],
                'jpeg' => ['image/jpeg'],
                'png' => ['image/png'],
                'webp' => ['image/webp'],
                'txt' => ['text/plain'],
            ],
            'max_files' => 3,
            'max_file_kilobytes' => 10 * 1024,
            'max_total_kilobytes' => 20 * 1024,
            'preview' => true,
            'camera' => false,
            'crop' => null,
            'help' => 'PDF, JPG, JPEG, PNG, WebP, atau TXT · maks. 3 file · 10 MB per file · total 20 MB.',
        ],
        'calendar_import' => [
            'label' => 'File kalender',
            'extensions' => ['xlsx', 'xls', 'csv'],
            'mime_by_extension' => [
                'xlsx' => ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip'],
                'xls' => ['application/vnd.ms-excel', 'application/x-ole-storage'],
                'csv' => ['text/csv', 'text/plain', 'application/csv', 'application/vnd.ms-excel'],
            ],
            'max_files' => 1,
            'max_file_kilobytes' => 5 * 1024,
            'max_total_kilobytes' => 5 * 1024,
            'preview' => false,
            'camera' => false,
            'crop' => null,
            'help' => 'XLSX, XLS, atau CSV · maks. 5 MB.',
        ],
    ],
];
